name: ci-AT_Component_one
'on':
  push:
    branches:
      - main
    paths:
      - '**/AT_CMP_FOLDER_ONE/**'
env:
  DOCKER_BUILD_FILE_PATH: ./AT_CMP_FOLDER_ONE/Dockerfile.build
  DOCKER_FILE_PATH: ./AT_CMP_FOLDER_ONE/Dockerfile.publish
  DOCKER_BUILD_CONTEXT: AT_CMP_FOLDER_ONE
  DOCKER_PUBLISH_CONTEXT: AT_CMP_FOLDER_ONE
  CONTAINER_NAME: test
  REPOSITORY_NAME: test
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build and Test
        run: docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_BUILD_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo
      - name: Runs docker
        run: docker run --name ${{ env.CONTAINER_NAME }} -d ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo
      - name: copy build files
        run: |-
          docker cp ${{ env.CONTAINER_NAME }}:/app/publish/ ./${{ env.DOCKER_PUBLISH_CONTEXT }}
          docker stop ${{ env.CONTAINER_NAME }}
          docker rm ${{ env.CONTAINER_NAME }}
      - name: Build and push image to container registry
        run: |-
          docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo
          docker push ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:demo
